### ISSUE TITLE
there is no requirements.txt

### ISSUE THREAD

**Issue by E4zily** [osumitsuha/Ragnarok#2]
title

**Comment by Hazuki-san** [comment]
Will be pushed after the dev branch is complete

**Comment by simonglob** [comment]
[here](https://github.com/osumitsuha/Ragnarok/blob/dev/requirements.txt)

**Comment by simonglob** [comment]
wait, nvm, it's an outdated one lol

**Comment by simonglob** [comment]
updated in [cc675f92c2d5a3ff9fdab89356c5ef283601e278](https://github.com/osumitsuha/Ragnarok/commit/cc675f92c2d5a3ff9fdab89356c5ef283601e278)
